import type { Role } from './types.ts';

export const RULESET_VERSION = 'LMPC-2011-R2024.1';

export const ROLE_LABELS: Record<Role, string> = {
  COMPLIANCE_ANALYST: 'Compliance Analyst',
  LEGAL_REVIEWER: 'Legal Reviewer / Officer',
  ADMIN: 'Administrator',
  VIEWER: 'Auditor (Viewer)',
};

export const ROLE_DESCRIPTIONS: Record<Role, string> = {
  COMPLIANCE_ANALYST: 'Preflights packages, manages evidence, reviews automated extractions.',
  LEGAL_REVIEWER: 'Authorized officer. Confirms results, records legal dispositions with audit reasons.',
  ADMIN: 'System administrator. Manages rules matrix, inspects immutable audit ledger.',
  VIEWER: 'Read-only access to historical screening records and reports.',
};

export const WORKFLOW = [
  'Capture package',
  'Canvas preflight',
  'Compress & upload',
  'Gemini vision',
  'Dynamic rules',
  'Officer review',
  'Audit report',
];

export interface StaticRuleDefinition {
  id: string;
  title: string;
  source: string;
  purpose: string;
  category: string;
  verificationMode: string;
  fieldTarget?: string;
  statutoryThreshold?: string;
  validationRegex?: string;
  applicabilityPredicate?: Record<string, unknown>;
}

export const RULES: StaticRuleDefinition[] = [
  {
    id: "RULE_6_1_E",
    title: "Maximum Retail Price (MRP)",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6(1)(e)",
    purpose: "Verify mandatory declaration of MRP inclusive of all taxes in Indian Rupees (₹ / Rs).",
    category: "MANDATORY_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "mrp",
    statutoryThreshold: "0.85",
    validationRegex: "(?:₹|INR|Rs\\.?)\\s*\\d+(?:\\.\\d{1,2})?",
    applicabilityPredicate: { exclude_export: true, package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_6_1_C",
    title: "Net Quantity Declaration",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6(1)(c), Rules 11–13",
    purpose: "Verify declaration of net quantity in standard units of weight, measure, or number with correct symbol format.",
    category: "MANDATORY_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "net_quantity",
    statutoryThreshold: "0.85",
    validationRegex: "\\d+(?:\\.\\d+)?\\s*(?:g|kg|ml|l|count|piece|units?)",
    applicabilityPredicate: { package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_6_1_A",
    title: "Manufacturer / Packer / Importer Entity & Address",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6(1)(a) & Rule 10",
    purpose: "Verify declaration of legal name and complete address of manufacturer, packer, or importer.",
    category: "MANDATORY_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "responsible_entity",
    statutoryThreshold: "0.80",
    validationRegex: ".+",
    applicabilityPredicate: { package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_6_1_D",
    title: "Date of Manufacture / Packing / Import",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6(1)(d)",
    purpose: "Verify declaration of month and year in which commodity was manufactured, packed, or imported.",
    category: "MANDATORY_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "date",
    statutoryThreshold: "0.80",
    validationRegex: "(?:0[1-9]|1[0-2])[\\/\\-]?(?:20\\d{2}|\\d{2})",
    applicabilityPredicate: { package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_6_1_N",
    title: "Consumer Care Information",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6(1)(n)",
    purpose: "Verify consumer grievance contact: name/office, address, telephone number, or email.",
    category: "MANDATORY_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "consumer_care",
    statutoryThreshold: "0.80",
    validationRegex: ".+",
    applicabilityPredicate: { package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_6_1_TAX",
    title: "Inclusive of All Taxes Declaration",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6(1)(e) & Rule 2(m)",
    purpose: "Verify that Maximum Retail Price declaration explicitly states inclusive of all taxes.",
    category: "MANDATORY_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "inclusive_taxes",
    statutoryThreshold: "1.0",
    validationRegex: "(?i)(?:incl(?:usive)?\\.?\\s*of\\s*all\\s*taxes|all\\s*taxes\\s*incl(?:usive)?\\.?)",
    applicabilityPredicate: { package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_6_1_ORIGIN",
    title: "Country of Origin Declaration",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6(1)(n)",
    purpose: "Verify mandatory country of origin declaration on the packaging.",
    category: "MANDATORY_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "country_origin",
    statutoryThreshold: "0.85",
    validationRegex: ".+",
    applicabilityPredicate: { package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_6_STICKER",
    title: "MRP Sticker Modification Compliance",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 6 Proviso",
    purpose: "Verify that any sticker applied to alter MRP declares a reduced price and does not obliterate original MRP.",
    category: "VISUAL_PREDICATE",
    verificationMode: "VISUAL_PREDICATE",
    fieldTarget: "sticker_mrp",
    statutoryThreshold: "1.0",
    applicabilityPredicate: { package_context: ["RETAIL", "ECOMMERCE"] },
  },
  {
    id: "RULE_11_WHENPACKED",
    title: "Third Schedule 'When Packed' Quantity Qualification",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 11 & Third Schedule",
    purpose: "Verify that commodities subject to volatile loss (soaps, lotions, creams, camphor) qualify net quantity as when packed.",
    category: "COMMODITY_SPECIFIC",
    verificationMode: "STATUTORY_LOOKUP",
    fieldTarget: "net_quantity",
    statutoryThreshold: "0.85",
    validationRegex: "(?i)when\\s*packed",
    applicabilityPredicate: { third_schedule_only: true },
  },
  {
    id: "RULE_14_DIMENSIONS",
    title: "Finished Fabric & Textile Dimensions",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 14",
    purpose: "Verify piece count and finished dimensions (length x width in standard metric units) for specified textile commodities.",
    category: "COMMODITY_SPECIFIC",
    verificationMode: "STATUTORY_LOOKUP",
    fieldTarget: "dimensions",
    statutoryThreshold: "0.85",
    validationRegex: "\\d+(?:\\.\\d+)?\\s*(?:m|cm|mm)\\s*(?:x|X|by)\\s*\\d+(?:\\.\\d+)?\\s*(?:m|cm|mm)",
    applicabilityPredicate: { commodity_category: ["TEXTILE_FINISHED_GOOD", "BED_SHEET", "SAREE", "TOWEL"] },
  },
  {
    id: "RULE_16_SHEETS",
    title: "Usable Sheets and Dimensions Declaration",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 16",
    purpose: "Verify declaration of number of usable sheets and dimensions of each sheet for foil, tissues, and paper rolls.",
    category: "COMMODITY_SPECIFIC",
    verificationMode: "STATUTORY_LOOKUP",
    fieldTarget: "usable_sheets",
    statutoryThreshold: "0.85",
    validationRegex: "\\d+\\s*(?:sheets|wipes|pulls|rolls|m|metres)",
    applicabilityPredicate: { commodity_category: ["SHEET_COMMODITY", "TISSUE", "FOIL"] },
  },
  {
    id: "RULE_24_WHOLESALE",
    title: "Wholesale Package Mandatory Declarations",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 24",
    purpose: "Verify responsible entity, commodity identity, and retail package count or net quantity on wholesale packages.",
    category: "WHOLESALE_DECLARATIONS",
    verificationMode: "DETERMINISTIC_SYNTACTIC",
    fieldTarget: "wholesale_declarations",
    statutoryThreshold: "0.85",
    validationRegex: ".+",
    applicabilityPredicate: { package_context: ["WHOLESALE"] },
  },
  {
    id: "RULE_25_EXPORT",
    title: "Export Package Domestic Sale Compliance",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 25",
    purpose: "Verify export packages sold domestically are relabeled or repacked to comply with Chapter II provisions.",
    category: "EXPORT_REGULATION",
    verificationMode: "WORKFLOW_GATE",
    fieldTarget: "export_compliance",
    statutoryThreshold: "1.0",
    applicabilityPredicate: { package_context: ["EXPORT"] },
  },
  {
    id: "RULE_26_A_SMALLQTY",
    title: "Small Quantity Exemption (≤10g / ≤10ml)",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 26(a)",
    purpose: "Determine exemption eligibility for packages containing 10 grams or 10 millilitres or less sold by weight or measure.",
    category: "EXEMPTION_GATE",
    verificationMode: "THRESHOLD_CALCULATION",
    fieldTarget: "net_quantity",
    statutoryThreshold: "1.0",
    applicabilityPredicate: { max_weight_g: 10, max_volume_ml: 10 },
  },
  {
    id: "RULE_26_A_TOBACCO",
    title: "Tobacco Exception to Small Quantity Exemption",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 26(a) Proviso",
    purpose: "Enforce statutory bar preventing tobacco and tobacco products from claiming Rule 26(a) small quantity exemption.",
    category: "EXEMPTION_OVERRIDE",
    verificationMode: "STATUTORY_EXCEPTION",
    fieldTarget: "commodity_type",
    statutoryThreshold: "1.0",
    validationRegex: "(?i)(?:tobacco|cigarette|bidi|gutka|khaini|chewing\\s*tobacco)",
    applicabilityPredicate: { is_tobacco: true },
  },
  {
    id: "RULE_26_A_PANMASALA",
    title: "Pan Masala Exception to Small Quantity Exemption",
    source: "Legal Metrology (Packaged Commodities) Second (Amendment) Rules, 2025 · Rule 26(a) Proviso",
    purpose: "Enforce statutory bar effective 1 Feb 2026 preventing pan masala packages from claiming Rule 26(a) small quantity exemption.",
    category: "EXEMPTION_OVERRIDE",
    verificationMode: "STATUTORY_EXCEPTION",
    fieldTarget: "commodity_type",
    statutoryThreshold: "1.0",
    validationRegex: "(?i)pan\\s*masala",
    applicabilityPredicate: { is_pan_masala: true, effective_from: "2026-02-01" },
  },
  {
    id: "RULE_26_B_FASTFOOD",
    title: "Fast Food Restaurant / Hotel Exemption",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 26(b)",
    purpose: "Determine exemption eligibility for fast food items packed by restaurants, hotels, or similar establishments.",
    category: "EXEMPTION_GATE",
    verificationMode: "STATUTORY_EXCEPTION",
    fieldTarget: "packer_type",
    statutoryThreshold: "1.0",
    applicabilityPredicate: { is_fast_food: true, establishment_type: ["RESTAURANT", "HOTEL"] },
  },
  {
    id: "RULE_26_C_DRUG",
    title: "DPCO 1995 Drug Formulation Exemption",
    source: "Legal Metrology (Packaged Commodities) Rules, 2011 · Rule 26(c)",
    purpose: "Determine exemption eligibility for scheduled or non-scheduled formulations covered under Drugs (Price Control) Order, 1995.",
    category: "EXEMPTION_GATE",
    verificationMode: "EXTERNAL_DEPENDENCY",
    fieldTarget: "drug_status",
    statutoryThreshold: "1.0",
    applicabilityPredicate: { is_drug_formulation: true, price_control_order: "DPCO_1995" },
  },
];
